config/routes.rb
Rails.application.routes.draw do

  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :street_address, :city, :state, :zip, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true

  has_many :addresses, through: :student_addresses
end

app/models/student_address.rb
class StudentAddress < ApplicationRecord
  belongs_to :student
  belongs_to :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
    redirect_to student_path(student)
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student = Student.find(params[:id])
    student.update(student_params)
    redirect_to student_path(student)
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <%= link_to "All Students", students_path %>
      <%= link_to "Create Student", new_student_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit student</h1>

<%= form_for(@student) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>All Students</h1>

<ul>
  <% @students.each do |student| %>
  <li class=student_<%= student.id %>>
    <%= link_to student.name, student_path(student) %><%= link_to "Delete", student_path(student), method: "delete" %></li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h1>Create new student</h1>

<%= form_for(@student) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %> 

app/views/students/show.html.erb
<h1><%= @student.name %></h1>